window.HighColoradoMedia=(()=>{
  const cache=new Map();
  const strip=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim();
  const freeLicense=s=>/CC0|CC BY|CC-BY|Creative Commons Attribution|Public domain|Public Domain|PD-/i.test(s||'');
  const score=(p,item,panorama=false)=>{const title=(item.title||'').toLowerCase(),desc=(item.description||'').toLowerCase();let s=0;p.name.toLowerCase().split(/\s+/).filter(w=>w.length>3).forEach(w=>{if(title.includes(w))s+=5;if(desc.includes(w))s+=2});if(title.includes('colorado')||desc.includes('colorado'))s+=5;if(/map|diagram|route|logo|flag|sign|plaque/.test(title))s-=15;const ratio=item.width&&item.height?item.width/item.height:1;if(ratio>1.25)s+=3;if(ratio>1.6)s+=2;if(/panorama|panoramic|360|equirectangular/.test(title+' '+desc))s+=panorama?18:6;if(panorama&&ratio>1.75)s+=7;return s};
  async function query(p){if(cache.has(p.id))return cache.get(p.id);const url='https://commons.wikimedia.org/w/api.php?'+new URLSearchParams({action:'query',format:'json',origin:'*',generator:'search',gsrsearch:`${p.name} Colorado mountain`,gsrnamespace:'6',gsrlimit:'16',prop:'imageinfo',iiprop:'url|extmetadata|dimensions',iiurlwidth:'1800'});const data=await fetch(url).then(r=>{if(!r.ok)throw Error('Commons request failed');return r.json()});const items=Object.values(data.query?.pages||{}).map(page=>{const ii=page.imageinfo?.[0]||{},m=ii.extmetadata||{},license=strip(m.LicenseShortName?.value||m.UsageTerms?.value);return{title:page.title||'',url:ii.thumburl||ii.url,fullUrl:ii.url,sourceUrl:ii.descriptionurl||('https://commons.wikimedia.org/wiki/'+encodeURIComponent(page.title)),width:ii.thumbwidth||ii.width,height:ii.thumbheight||ii.height,artist:strip(m.Artist?.value)||'Wikimedia Commons contributor',license,licenseUrl:m.LicenseUrl?.value||'',description:strip(m.ImageDescription?.value),free:freeLicense(license)}}).filter(x=>x.url&&x.free);items.sort((a,b)=>score(p,b)-score(p,a));const result={hero:items[0]||null,panorama:[...items].sort((a,b)=>score(p,b,true)-score(p,a,true))[0]||null,items:items.slice(0,8)};cache.set(p.id,result);return result}
  const credit=(item,compact=false)=>item?`${compact?'':'Photo: '}${item.artist}${item.license?' · '+item.license:''}`:'';
  return{query,credit,strip};
})();
